jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
    header: ${JWT_ACCESS_HEADER}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}
    header: ${JWT_REFRESH_HEADER}
